### ISSUE TITLE
[BUG] Assessed principles are considered as not assessed

### ISSUE THREAD

**Issue by dan-tang-ssd** [stats4sd/aec_portfolio#112]
**Describe the bug**
Assessed principles are considered as not assessed

**To Reproduce**
My Institution > A new portfolio > SHOW INITIATIVES > Initiative ABC > Click Access Principles button >
Click Principle 1, do not change anything, keep score as 0, click Save and Next button
Principle 2, do not change anything, keep score as 0, click Save and Next button
Principle 3, do not change anything, keep score as 0, click Save and Close button

Suppose Principle 1, 2, 3 should have 0 score. But only prinicple 1 is assessed with 0 score.

Er... I am not quite sure whether it is normal behaviour, but we have different behaviour for principle 1 and principle 2, 3 now...

**Expected behavior**
Principle 1, 2, 3 should have 0 score.

**Screenshots**

![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/8474d3bc-b201-4114-9512-584f18904d7c)

Click principle 1 to start accessment
![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/442cc274-abd1-4217-b70d-cc8ffaa5901f)

![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/9a8dbf53-d817-49ca-bc54-aa50de7e9dbb)

![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/f33ff0ab-0388-40ba-baff-446a73e8291d)

![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/5ca8a73a-1611-4bc1-be68-ec05d4009c3c)

Principle 1, 2, 3 are considered as not assessed
![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/2a2d3c38-a877-430c-8c11-8e4ffac5b98f)

Refresh browser
Only principle 1 is considered as assessed
![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/57830803-2064-49a0-a69d-16399e89f888)

**Comment by dave-mills** [comment]
Fixed in #134
