### ISSUE TITLE
Add an option to delete initiative and portfolios

### ISSUE THREAD

**Issue by dan-tang-ssd** [stats4sd/aec_portfolio#113]
**Is your feature request related to a problem? Please describe.**
Currently there is no option to delete an initiative. We need to be able to delete an initiative from a portfolio.

**Describe the solution you'd like**
Add delete button in Initiatives.

**Describe alternatives you've considered**
Um... no alternatives...

**Additional context**
We need this feature to remove double entry or testing data for initiatives.

![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/21962154-113d-4204-8f1f-b0afc052a9ae)

Related email:
[Comments by GIZ - AW Agroecology Funding Portfolio Assessment Tool - Invitation.zip](https://github.com/stats4sd/aec_portfolio/files/11956416/Comments.by.GIZ.-.AW.Agroecology.Funding.Portfolio.Assessment.Tool.-.Invitation.zip)

**Comment by dave-mills** [comment]
Adding the need to delete all initiatives from a portfolio when a portfolio is deleted, as I think it fits technically with this issue.
