### ISSUE TITLE
Entering additional criteria need to be improved, clearer etc

### ISSUE THREAD

**Issue by dan-tang-ssd** [stats4sd/aec_portfolio#114]
**Is your feature request related to a problem? Please describe.**
Institutional assessor may not know where to find additional criteria.

**Describe the solution you'd like**
Entering additional criteria need to be improved, clearer etc

**Describe alternatives you've considered**
Add tutorial video to show steps by steps instructions

**Additional context**

![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/b2ff6f28-92f6-4699-b01d-83980fee6ee6)

Related Email:
[Comments by GIZ - AW Agroecology Funding Portfolio Assessment Tool - Invitation.zip](https://github.com/stats4sd/aec_portfolio/files/11956451/Comments.by.GIZ.-.AW.Agroecology.Funding.Portfolio.Assessment.Tool.-.Invitation.zip)

**Comment by dave-mills** [comment]
TODO: 

[ ] - Auto refresh the page when a user changes the "has_additional_criteria" option in institution settings (so the extra tab can appear / disappear)
[ ] - Add help text entry onto that checkbox. 
[ ] - Add short video explaining additional criteria

[ ] - Add Additional criteria score onto the initiative card in the main list
[ ] - Add Additional Criteria overall score as extra summary on the dashboard. 
  - Maybe as a new tab? WIth the principle assessment style visualisation? 


---

**Comment by dave-mills** [comment]
Leaving the extra dashbaord summary for a V2 feature, given the uncertain future of "additional criteria"
