### ISSUE TITLE
Check that history of changes is kept accurately

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/aec_portfolio#148]
From the tech spec: 

•	Even after completion, the redline assessment can be edited by institutional members.
–	A history of changes is kept by the system, and is available to institutional managers for internal review purposes.
–	If at any point a redline entry is changed to be marked as “Yes”, the initiative’s score becomes 0, regardless of the answers given to the other stages of assessment.

**Comment by dave-mills** [comment]
At present, there is a "revisions" table, which is storing changes to PrincipleAssessment properties. We need to check:

- [ ] does it keep changes to AssessmentRedline properties?
- [ ] does it keep changes to AdditionalCriteriaAssessment Properties?

In an ideal world, we should also keep track of the links between PrincipleAssessment + ScoreTag / CustomScoreTag and also AdditionalCriteriaAssessment + AdditionalCriteriaScoreTag / AdditionalCriteriaCustomScoreTag, but that is more complex and I think quite an edge case, so we can push this to a version 2.0 in favour of other issues. 

We do need a way of presenting these changes via the UI to Institutional Admins and Site Managers/Admins. We should add a simple page with the full list of changes, (including the user who made the change, the date, the old and new values), and make it filterable by Initiative.

**Comment by dan-tang-ssd** [comment]
I have created a new initiative for testing.

---

After assessing 13 red flags, 13 revisions records added as expected.

![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/574dcba7-30e4-4002-bb9d-38871f8f4340)

![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/3771a0fd-eef6-4777-bd87-c88f2c89b19a)

---

After assessing 13 principles, 13 revisions records added as expected.

![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/b9ed8d73-8c4e-478f-be01-7a30d0c015bd)

![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/ac6fa017-6a15-46ed-9374-e2716523e82f)

---

After assessing 1 additional criteria, 2 revisions records added.
revisionable_id is same but revisionable_type are App\Models\AdditionalCriteriaAssessment and App\Models\PrincipleAssessment.

Question: Um... Why we have App\Models\PrincipleAssessment after assessing additional criteria? 

![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/a6e58b02-23f9-4110-ad89-1d4a0ac0a4ce)

![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/fb020bdf-12c1-48ee-9cca-94be54ee56c5)

**Comment by dan-tang-ssd** [comment]
Performed two more testings.

1. Assess Principles, change 9 / 13 principles to na. 18 revisions records added as expected.
For each prinicple, one record for na, another record to change rating from original value 1.00 to NULL.

![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/7bd2302d-248d-4767-bc20-7db5a471a439)

![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/e0a67963-12f3-4a29-8733-c8c53a518d72)

---

2. Assess Red Flags, change one red flag from No to Yes, initative score changed to 0 as expected.

![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/88b7c01c-b133-4b90-819c-a13e41e28565)

![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/7c9d70fe-fad7-44bf-8737-bc9394c699c7)

![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/f2548f38-5f6d-4763-b602-f34cdb82e968)

**Comment by dave-mills** [comment]
> Question: Um... Why we have App\Models\PrincipleAssessment after assessing additional criteria?

Interesting find. I took a look at the save function on the PrincipleAssessmentModal Vue component, and found something that explains it: 

```javascript
async function save(nextAction) {

  // ...stuff happens, and then: 


    await axios.patch(`/principle-assessment/${props.principleAssessment.id}`, props.principleAssessment)
    let url = `/principle-assessment/${props.principleAssessment.id}`

    // check if we are saving a principle-assessment or additional-criteria-assessment
    if (props.assessmentType === "additional") {
        url = `/additional-assessment/${props.principleAssessment.id}`
    }

        const res = await axios.patch(url, props.principleAssessment)

    emit(nextAction)

}
```

The first axios.patch is probably the original, and then we swapped to the version where the url changes if it's an additional assessment. I expect at some point a merge occured that put both versions back together.
