### ISSUE TITLE
Standardise the way on data visualisation dashboard, summary report PDF file generation, micro data excel file extraction. The same way can be applied for one project, one portfolio, one institution, ALL projects, or just a list of project IDs.

### ISSUE THREAD

**Issue by dan-tang-ssd** [stats4sd/aec_portfolio#41]

**Comment by dan-tang-ssd** [comment]
These issues have been resolved in PR #51 and PR #63.

**Comment by dave-mills** [comment]
> These issues have been resolved in PR #51 and PR #63.

@dan-tang-ssd - In future, please close an issue once it's resolved. No need to stand on ceremony / wait for me to close it.
