### ISSUE TITLE
Excel template for importing initatives is missing fields

### ISSUE THREAD

**Issue by emilynevitt** [stats4sd/aec_portfolio#89]
The excel file downloaded from the 'import initiatives' page is missing some fields that are required on the web form, such as the funding source and geographical region and country. It also includes an incomplete second example row. 
<img width="1113" alt="Screenshot 2023-06-28 at 11 13 34" src="https://github.com/stats4sd/aec_portfolio/assets/37402972/23ee94b0-556b-44ea-9068-42816674d9c7">

**Comment by dave-mills** [comment]
2 parts:

- [ ] for init. level data - check and add missing fields (is own funds or external funding?) 
- [ ] "quick" fix for multi-level data is to add instructions to users:
 - add initiatives with "core" info in the Excel template;
 - upload/ import
 - add extra details (locations, funding sources etc) in platform.  

long term fix is to investigate adding multi-level data into excel template.
