### ISSUE TITLE
Assessment Status is not easy to understand

### ISSUE THREAD

**Issue by dan-tang-ssd** [stats4sd/aec_portfolio#94]
I tried to find some initiatives by specifying status.
I can search by red line status and principle status, as we have two separate status for red line and principle respecitvely.
In search result, there is only one status showed. I cannot figure out which status (red line or priniciple status) will be showed.

Will it be clearer and more informative if we show both red line status and principle status?

**To Reproduce**
My institutions > PORTFOLIOS > SHOW INITIATIVES > Filters

![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/aaa3a536-5686-439b-8950-644d5a3344a2)

**Comment by dave-mills** [comment]
Marking this as paused for now until we get more feedback from users during the pilot.

**Comment by dave-mills** [comment]
Considering this fixed with #207; will do a final review of help text just prior to public release with support from the Coalition.
